spring:
  datasource:
    url: jdbc:sqlite:${user.dir}/video-collect.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/init-sqlite.sql
